# Generated by Django 4.1.7 on 2023-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joke',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
