# Generated by Django 4.1.7 on 2023-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_customuser_joke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joke',
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, to='scraper.data'),
        ),
    ]
