# Generated by Django 4.1.7 on 2023-03-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_customuser_joke_customuser_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, null=True, to='scraper.data'),
        ),
    ]
