# Generated by Django 4.1.7 on 2023-03-30 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_customuser_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 30, 6, 36, 25, 471981, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
