# Generated by Django 4.1.7 on 2023-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Claps',
            field=models.IntegerField(default=0),
        ),
    ]
