# Generated by Django 4.1.7 on 2023-04-01 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_claps'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 1, 4, 7, 7, 57382, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
