# Generated by Django 4.1.7 on 2023-04-01 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_data_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='liked_posts',
            new_name='favourite_posts',
        ),
        migrations.AlterField(
            model_name='data',
            name='Title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='FavPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favs', to='scraper.data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
